### ISSUE TITLE
PS

### ISSUE THREAD

**Issue by xmarinin** [JKearnsl/nowappAPI#1]
Public repository with our token? Be careful, please.

**Comment by xmarinin** [comment]
@JKearnsl JKearnsl

**Comment by JKearnsl** [comment]
@xmarinin , Вы откроете api? Я уже писал Вам на почту, но не дождался ответа и начал писать обертку над вашим приложением. Я был удивлен, потому что вы используете американские сервера для хранения данных русских пользователей в такое время: авторизация происходит через google и тд, а позиционируете себя как отечественную замену инстаграма, ловя хайп на этом, выпуская приложение именно сейчас.
